# Generated by Django 6.0.4 on 2026-05-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('sales_volume', models.PositiveIntegerField(default=0)),
                ('stock_level', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('margin_percent', models.FloatField(default=0)),
                ('season', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
